name: paperboat_lite
description: "Invoice Totaler is a seamless and simple web app that effortlessly calculates totals and generates professional invoices. With its user-friendly interface, you can quickly export or print your completed invoice as a high-quality PDF, making billing and record-keeping a breeze."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  responsive_framework: ^1.5.1
  google_fonts: ^4.0.4
  pdf: ^3.11.3
  printing: ^5.14.2
  file_picker: ^10.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Declare custom fonts here
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
